builds:
  - binary: homelab
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: homelab 
    homepage: https://github.com/built-home/homelab
    tap:
      owner: built@home
      name: homelab
    commit_author:
      name: teaglebuilt
      email: dillan.teagle.va@gmail.com

checksum:
  name_template: 'checksums.txt'
