services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/portainer/data:/data
    networks:
      - phantom-net

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    volumes:
      - ${STORAGE}/deluge/config:/config
      - ${STORAGE}/deluge/downloads:/downloads # Edit the Download directory in Preferences
    expose:
      - '8112'
    environment:
      DELUGE_LOGLEVEL: error
      PUID: 0
      PGID: 0
      TZ: America/Chicago
      UMASK_SET: 022
    networks:
      - phantom-net


networks:
  phantom-net:
    name: phantom-net