services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/portainer/data:/data
    networks:
      - phantom-net

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard-client
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - ALLOWEDIPS=0.0.0.0/0
    ports:
      - "51820:51820/udp"
      - "8112:8112"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    volumes:
      - ${STORAGE}/deluge/config:/config
      - ${STORAGE}/deluge/downloads:/downloads # Edit the Download directory in Preferences
    network_mode: "service:wireguard"
    environment:
      DELUGE_LOGLEVEL: error
      PUID: 0
      PGID: 0
      UMASK_SET: 022
    networks:
      - phantom-net


networks:
  phantom-net:
    name: phantom-net