{{- if .Values.ingress_route.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grafana-ingress-middleware
spec:
  stripPrefix:
    prefixes:
      - /grafana
{{- end -}}